---
title: "MDSR Chapter 4 Prog Nbk"
author: "TJ Schaeffer"
date: "Due: January 10, 2019"
output: html_notebook
---

# Front matter

```{r echo=TRUE, message=FALSE}
# always clean up R environment
rm(list = ls())

# load all packages here
library(mdsr)
library(tidyverse)
library(lubridate)
library(Lahman)
library(mosaic)
library(nycflights13)

# user-defined functions here (if any)


# load data
data("presidential")  # from ggplot2 (via `tidyverse`)
data("Teams")         # from Lahman
data("flights")       # from nycflights13

```


# Chapter Notes

## Section 4.1  

*[Note: include a placeholder for each section even if there's no programming required]*


### Sec 4.1.1

```{r}
# p. 64; inspect the data... it's small so we just print it directly
presidential
```

```{r}
# p. 65
presidential %>%
  select(name, party)
```

```{r}
# p. 65
presidential %>%
  filter(party == "Republican")
```

```{r}
# p. 65; minimize nested syntax
select(
  filter(presidential, start > "1973-01-01" & party == "Democratic"), name)
```


```{r}
# p. 66; minimize nested syntax
presidential %>%
  filter(start > "1973-01-01" & party == "Democratic") %>%
  select(name)
```


```{r}
# p. 67
mypresidents <- 
  presidential %>%
  mutate(term.length = interval(start, end) / eyears(1))

mypresidents
```


```{r}
# p. 67
mypresidents <- 
  mypresidents %>%
  mutate(elected = year(start) - 1)

mypresidents
```



```{r}
# p. 68
mypresidents <- 
  mypresidents %>%
  mutate(elected = ifelse((elected %in% c(1962, 1973)), NA, elected))

mypresidents
```


```{r}
# p. 68
mypresidents <-
  mypresidents %>%
  rename(term_length = term.length) 

mypresidents
```


### Section 4.1.3 

```{r}
# p. 69
mypresidents %>% 
  arrange(desc(term_length))
```

```{r}
# p. 69
mypresidents %>% 
  arrange(desc(term_length), party, elected)
```


### Section 4.1.4

```{r}
# p. 70
mypresidents %>%
  summarize(
    N = n(), 
    first_year = min(year(start)), 
    last_year = max(year(end)), 
    num_dems = sum(party == "Democratic"), 
    years = sum(term_length), 
    avg_term_length = mean(term_length))
```

```{r}
# p. 71
mypresidents %>% 
  group_by(party) %>%
  summarize(
    N = n(), 
    first_year = min(year(start)), 
    last_year = max(year(end)), 
    num_dems = sum(party == "Democratic"), 
    years = sum(term_length),
    avg_term_length = mean(term_length))
```

## Section 4.2
```{r}
# p. 72
library(Lahman)
dim(Teams)
```

```{r}
# p. 72
mets <- Teams %>% filter(teamID == "NYN")
myMets <- mets %>% filter(yearID %in% 2004: 2012)
myMets %>% select(yearID, teamID, W, L)
```

```{r}
# p. 72
nrow(mets)
```

```{r}
# p. 73
select(filter(mets, teamID == "NYN" & yearID %in% 2004:2012), yearID, teamID, W, L)
```

```{r}
# p. 73
Teams %>%
  select(yearID, teamID, W, L) %>%
  filter(teamID == "NYN" & yearID %in% 2004:2012)
```

```{r}
# p. 74
metsBen <- Teams %>% 
  select(yearID, teamID, W, L, R, RA) %>% 
  filter(teamID == "NYN" & yearID %in% 2004:2012)
metsBen
```

```{r}
# p. 74
metsBen <- metsBen %>% rename(RS = R)
metsBen
```

```{r}
# p. 74
metsBen <- metsBen %>% mutate(WPct = W / (W + L))
metsBen
```

```{r}
# p. 75
metsBen <- metsBen %>% mutate(WPct_hat = 1 / (1 + (RA/RS)^2))
metsBen
```

```{r}
# p. 75
metsBen <- metsBen %>% mutate(W_hat = WPct_hat * (W + L))
metsBen
```

```{r}
# p. 75
filter(metsBen, W >= W_hat)
```

```{r}
# p. 76
filter(metsBen, W < W_hat)
```

```{r}
# p. 76
arrange(metsBen, desc(WPct))
```

```{r}
# p. 76
metsBen %>%
  mutate(Diff = W - W_hat) %>%
  arrange(desc(Diff))
```

```{r}
# p. 77
favstats(~ W, data = metsBen)
```

```{r}
# p. 77
metsBen %>%
  summarize(
    num_years = n(), 
    total_W = sum(W), 
    total_L = sum(L), 
    total_WPct = sum(W) / sum(W + L), 
    sum_resid = sum(W - W_hat))
```

```{r}
# p. 77
metsBen <- metsBen %>%
  mutate(
    gm = ifelse(yearID == 2004, "Duquette",
         ifelse(yearID >= 2011, "Alderson", "Minaya"))
  )
```


```{r}
# p. 77
metsBen %>%
  group_by(gm) %>%
  summarize(
    num_years = n(), 
    total_W = sum(W), 
    total_L = sum(L), 
    total_WPct = sum(W) / sum(W + L), 
    sum_resid = sum(W - W_hat)) %>%
  arrange(desc(sum_resid))
```

```{r}
# p. 78
Teams %>% 
  select(yearID, teamID, W, L, R, RA) %>% 
  filter(teamID == "NYN" & yearID %in% 2004:2012) %>%
  rename(RS = R) %>%
  mutate(
    WPct = W / (W + L), 
    WPct_hat = 1 / (1 + (RA/RS)^2), 
    W_hat = WPct_hat * (W + L),
    gm = ifelse(yearID == 2004, "Duquette",
         ifelse(yearID >= 2011, "Alderson", "Minaya"))) %>%
  group_by(gm) %>%
  summarize(
    num_years = n(), total_W = sum(W), total_L = sum(L), total_WPct = sum(W) / sum(W + L), sum_resid = sum(W- W_hat)) %>%
  arrange(desc(sum_resid))
  
```

```{r}
# p. 78
Teams %>% select(yearID, teamID, franchID, W, L, R, RA) %>%
  filter(yearID %in% 2004:2012) %>%
  rename(RS = R) %>%
  mutate(
    WPct = W / (W + L), WPctHat = 1 / (1 + (RA/RS)^2),
    WHat = WPctHat * (W + L)) %>%
  group_by(franchID) %>%
  summarize(
    numYears = n(), totalW = sum(W), totalL = sum(L), totalWPct = sum(W) / sum(W + L), sumResid = sum(W - WHat)) %>%
  arrange(sumResid) %>%
  print(n = 6)
```

## Section 4.3

### Section 4.3.1

```{r}
# p. 79
library(nycflights13)
head(flights, 3)
```

```{r}
# p. 80
head(airlines, 3)
```

```{r}
# p. 80
flightsJoined <- flights %>%
  inner_join(airlines, by = c("carrier" = "carrier"))
glimpse(flightsJoined)
```

```{r}
# p. 81
flightsJoined %>%
  select(carrier, name, flight, origin, dest) %>% 
  head(3)
```

```{r}
# p. 81
nrow(flights)
nrow(flightsJoined)
```

### Section 4.3.2

```{r}
# p. 81
airportsPT <- filter(airports, tz == -8)
nrow(airportsPT)
```

```{r}
# p. 81
nycDestsPT <- flights %>% inner_join(airportsPT, by = c("dest" = "faa"))
nrow(nycDestsPT)
```

```{r}
# p. 82
nycDests <- flights %>% left_join(airportsPT, by = c("dest" = "faa"))
nrow(nycDests)
sum(is.na(nycDests$name))
```

## Section 4.4

```{r}
# p. 82
manny <- filter(Batting, playerID == "ramirma02")
nrow(manny)
```

```{r}
# p. 82
manny %>% summarize(
  span = paste(min(yearID), max(yearID), sep = "-"), 
  numYears = n_distinct(yearID), numTeams = n_distinct(teamID),
  BA = sum(H) / sum(AB), tH = sum(H), tHR = sum(HR), tRBI = sum(RBI))
```

```{r}
# p. 83
manny %>%
  group_by(teamID) %>%
  summarize(
    span = paste(min(yearID), max(yearID), sep = "-"), 
    numYears = n_distinct(yearID), 
    numTeams = n_distinct(teamID),
  BA = sum(H) / sum(AB),
  tH = sum(H), tHR = sum(HR), tRBI = sum(RBI)) %>%
  arrange(span)
```

```{r}
# p. 83
manny %>%
  group_by(lgID) %>%
  summarize(
    span = paste(min(yearID), max(yearID), sep = "-"), 
    numYears = n_distinct(yearID), 
    numTeams = n_distinct(teamID),
    BA = sum(H) / sum(AB), 
    tH = sum(H), 
    tHR = sum(HR), 
    tRBI = sum(RBI)) %>%
  arrange(span)
```

```{r}
# p. 83
manny %>%
  filter(HR >= 30) %>%
  nrow()
```

```{r}
# p. 84
manny %>%
  group_by(yearID) %>%
  summarize(tHR = sum(HR)) %>%
  filter(tHR >= 30) %>%
  nrow()
```

```{r}
# p. 84
Master %>% filter(nameLast == "Ramirez" & nameFirst == "Manny")
```

```{r}
# p. 85
Batting %>%
  filter(playerID == "ramirma02") %>%
  inner_join(Master, by = c("playerID" = "playerID")) %>%
  group_by(yearID) %>%
  summarize(
    Age = max(yearID - birthYear), 
    numTeams = n_distinct(teamID), 
    BA = sum(H) / sum(AB), 
    tH = sum(H), 
    tHR = sum(HR), 
    tRBI = sum(RBI)) %>%
  arrange(yearID)
```

```{r}
# p. 85
mannyBySeason <- Batting %>%
  filter(playerID == "ramirma02") %>%
  inner_join(Master, by = c("playerID" = "playerID")) %>%
  group_by(yearID) %>%
  summarize(
    Age = max(yearID - birthYear), 
    numTeams = n_distinct(teamID), 
    BA = sum(H) / sum(AB), 
    tH = sum(H), 
    tHR = sum(HR), 
    tRBI = sum(RBI), 
    OBP = sum(H + BB + HBP) / sum(AB + BB + SF + HBP), 
    SLG = sum(H + X2B + 2*X3B + 3*HR) / sum(AB)) %>%
  mutate(OPS = OBP + SLG) %>%
  arrange(desc(OPS))
mannyBySeason
```

```{r}
# p. 86
mlb <- Batting %>%
  filter(yearID %in% 1993:2011) %>%
  group_by(yearID) %>%
  summarize(lgOPS = sum(H + BB + HBP, na.rm = TRUE) / sum(AB + BB + SF + HBP, na.rm = TRUE) + sum(H + X2B + 2*X3B + 3*HR, na.rm = TRUE) / sum(AB, na.rm = TRUE))
mlb
```

```{r}
# p. 87
mannyRatio <- mannyBySeason %>%
  inner_join(mlb, by = c("yearID" = "yearID")) %>%
  mutate(OPSplus = OPS / lgOPS) %>%
  select(yearID, Age, OPS, lgOPS, OPSplus) %>%
  arrange(desc(OPSplus))
mannyRatio
```

```{r}
# p. 87
ripken <- Batting %>% filter(playerID == "ripkeca01")
nrow(inner_join(ripken, mlb, by= c("yearID" = "yearID")))
nrow(inner_join(mlb, ripken, by = c("yearID" = "yearID")))
```

```{r}
# p. 88
ripken %>%
  left_join(mlb, by = c("yearID" = "yearID")) %>% 
  select(yearID, playerID, lgOPS) %>%
  head(3)
```

```{r}
# p. 88
mlb %>%
  left_join(ripken, by = c("yearID" = "yearID")) %>%
  select(yearID, playerID, lgOPS)
```

## Section 4.5

*[Note: include a placeholder for each section even if there's no programming required]*


